language: c
sudo: required
services:
  - docker
env:
  global:
    - secure: "Tnp4xTdojw6P2XGRCe8LvNx1stBqCaFHUV1msf97cqAKzGA3KaOTk7ZWOftpErzMuv/GatBgdFuZjmzKNulr8v9bDjYB0bjsA+kMRc3MQ/Kqiq8y9nk7H/Ee2FmB/T12qWrgbIuUIfARYT30WUUTezcCySLJJalZzl6VAbRhmYdhgYEYbinjPZ19jytWJijUNTHG1AvmldB1DiPJJZZhmgiRBs4a7rECGdGeiXuV9GuBhadEFScgPDhVvkFJKJ3NgQF+V5E03JsBR1WvnM8DcpLaqzoYRwtO69QzhYAaKBtJyi4+QT9CTWYtRZ8NZCd7TSBI6C8JbRHWQgBtLA+uNKFZSIRr2PaJgxcJH8A8rbpwXv4giff993VAXOmaQWQfJE2AvFoi8sCDo01GcF5FLVGH5AEac0h7W3EXpF/GXmaTtewN166NzpDb3MFAmh8BNhx5AtPaZOBzIaUXB73v+chT5czmgW68DxUJk/oQfmh+UFUkXcCkiNziaIUyiE9uT7sxaFhHlJ03z5JDr04s7blJScPd9griWmwLL/TCa5F17LbKnshvEfxmrJp9MR4PmXPkngX3/WthyGI+ZKwrXh43sSu0G8g3//4B5u9AI4mTHaXILB9hy125R06KgivYWvp9g3rxOZmNgXPktAX7rxempHms7pds46BMx2P0Gew="
    - secure: "YLVsqRD/YVUSgVx0vo6Aug/q0PxEU/voR2ZZwkweEPSKSmlrll9cJxtF9m60fEN+v20Q0Rxg/z8xxAZZwGqH9uaFOAhF2OuQGdwtKSz0DdUtW2gLK8I0+bMAkgNHuV3e3dsITFzRtcZG5UJNCBRUVPsgzrXfgkqeDfA2sc/VH5n12mjr7oT1ATTnF4ZHfAKzFw9qJUl2TKp7atsUrpATdY+YSC06KX/LC438MZAfWdyF31l4JatVXI0bE91V3xEl8sX2ZCmGIr6XOB6CbC8sHF5xO+cgbtw3RfYeWh9nIKTIKQlxwnG2i8Z7Flm+yBDqaIrteuUfLpy7G6k0VN4P3jHyX2PiDJkr5KIVfVutnY9fSmEQbXbLcDE8VfnJevPlIX2Qeh2jY/Ke2/nf+bVe/EcThYffChEkvBhXC3eq5oq7ldzw+baP+2iuagYUVWhpCqMiNeF0tNBHKKKyZQpGfSZ1gNewfB/YSkPvojgq3ZfuXiHXJpzsMZscv3QLSlDejQq0v2LWFoqCcLyLY6/AgFIm9N0JwNH4QdltOb03P4P49cZcCfwmemc66QXMcU8eI/S41fJrWRh65hgDovx9qXaJGgm82m6uqsL2AGvPiNDrweb+uB7Hnbz1nP19aXaoajsJ4qmV2IaGXSNGLGgxoLyht1gEKJ03c+WCquPLXVA="
script:
  - ./scripts/build.sh
after_success:
  - ./scripts/deploy.sh
